[package]
name = "caelix-bin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "caelix"
path = "src/main.rs"

[dependencies]
caelix-api = { path = "../caelix-api" }
caelix-service = { path = "../caelix-service" }
caelix-config = { path = "../caelix-config" }
caelix-message = { path = "../caelix-message" }
caelix-runtime = { path = "../caelix-runtime" }
caelix-cli = { path = "../caelix-cli" }
caelix-memory = { path = "../caelix-memory" }
caelix-http = { path = "../caelix-http", optional = true }
chrono = { version = "0.4.38", features = ["serde"] }
caelix-tui = { path = "../caelix-tui", optional = true }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
inventory.workspace = true

[features]
default = ["cli"]
cli = []
http-server = ["dep:caelix-http"]
tui = ["dep:caelix-tui"]
all= ["dep:caelix-http","dep:caelix-tui"]
ast = ["caelix-service/ast"]
ast-rust = ["caelix-service/ast-rust"]
ast-python = ["caelix-service/ast-python"]
ast-ts = ["caelix-service/ast-ts"]
ast-go = ["caelix-service/ast-go"]
ast-c = ["caelix-service/ast-c"]
