[package]
name = "caelix-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
caelix-service = { path = "../caelix-service" }
tokio.workspace = true
ratatui.workspace = true
crossterm.workspace = true
futures.workspace = true
async-trait.workspace = true
chrono.workspace = true
thiserror.workspace = true
serde.workspace = true
ratatui-textarea = "0.9"
termimad = "0.31"
