[package]
name = "caelix"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.80"
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.14"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
uuid = { version = "1.8.0", features = ["v4"] }
chrono = "0.4.38"
thiserror = "1.0.61"
dirs = "5.0.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "blocking", "multipart", "stream", "socks"] }
walkdir = "2.5.0"
anyhow = "1.0.102"
futures = "0.3.32"

[profile.dev]
debug = 2        # 完整调试符号（关键）
opt-level = 0    # 关闭优化
panic = "unwind" # 不要 abort
strip = false     # 不剥离符号