[package]
name = "caelix-config"
version = "0.1.0"
edition = "2024"

[features]
default = []
logging = ["tracing-subscriber"]

[dependencies]
caelix-api = { path = "../caelix-api" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
dirs.workspace = true
anyhow.workspace = true
tracing.workspace = true
once_cell.workspace = true
walkdir.workspace = true
thiserror.workspace = true
rust-embed.workspace = true
tracing-subscriber = { workspace = true, optional = true }

[dev-dependencies]
tempfile = "3"
