[package]
name = "caelix-task"
version = "0.1.0"
edition = "2024"

[dependencies]
caelix-api = { path = "../caelix-api" }
caelix-message = { path = "../caelix-message" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
dirs.workspace = true
cron.workspace = true
anyhow.workspace = true
async-trait.workspace = true
dashmap.workspace = true
